#!/usr/bin/env bash
# Build, extract and serve an Ultiorganizer release package in an isolated
# Docker stack so install.php can be run against it by hand.
#
# Usage: release-test.sh setup|reset|smoke|teardown [--help]
#
# Environment overrides:
#   UO_TEST_ROOT     test directory (default: <repo parent>/ultiorganizer-release-test)
#   UO_TEST_PROJECT  compose project name (default: uo-release-test)
#   UO_TEST_PORT     host port for the app (default: 8081)
#   UO_TEST_ARCHIVE  use this existing package instead of building one (setup)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
TEST_ROOT="${UO_TEST_ROOT:-$(dirname "${ROOT_DIR}")/ultiorganizer-release-test}"
PROJECT="${UO_TEST_PROJECT:-uo-release-test}"
PORT="${UO_TEST_PORT:-8081}"
STATE_FILE="${TEST_ROOT}/.release-test-env"
COMPOSE_FILE="${TEST_ROOT}/compose.yaml"
BASE_URL="http://localhost:${PORT}"

# Any image with coreutils works; mariadb is already pulled by this stack.
HELPER_IMAGE="mariadb:10.11"

usage() {
    sed -n '2,11p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

compose() {
    docker compose -p "${PROJECT}" -f "${COMPOSE_FILE}" "$@"
}

# The web server writes as www-data (uid 33) and step 6 of the wizard hardens
# conf/ to 0555, so the host user can neither chown nor delete the tree
# afterwards. Borrow root from a throwaway container.
chown_test_root() {
    docker run --rm -v "${TEST_ROOT}:/work" "${HELPER_IMAGE}" chown -R "$1" /work
}

load_state() {
    if [[ ! -f "${STATE_FILE}" ]]; then
        echo "error: ${STATE_FILE} not found; run 'release-test.sh setup' first" >&2
        exit 1
    fi
    # shellcheck source=/dev/null
    source "${STATE_FILE}"
}

write_compose_file() {
    cat > "${COMPOSE_FILE}" <<EOF
# Generated by docs/ai/test-release-install/scripts/release-test.sh.
# The web root is the extracted release package, not the git checkout.
services:
  app:
    build:
      context: ${ROOT_DIR}
      dockerfile: docs/dev/Dockerfile.app
    depends_on:
      db:
        condition: service_healthy
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      XDEBUG_MODE: "off"
    ports:
      - "${PORT}:80"
    volumes:
      - ./${PACKAGE_NAME}:/var/www/html
      - ${ROOT_DIR}/docs/dev/php.dev.ini:/usr/local/etc/php/conf.d/zz-local-dev.ini:ro

  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ultiorganizer
      MYSQL_USER: ultiorganizer
      MYSQL_PASSWORD: ultiorganizer
      MYSQL_ROOT_PASSWORD: changeme
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=127.0.0.1", "--user=root", "--password=changeme"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - release-test-db-data:/var/lib/mysql

volumes:
  release-test-db-data:
EOF
}

# Removes every previously extracted package, not just the current one: the
# directory name carries the commit hash, so building at a new commit would
# otherwise leave the old tree behind, www-data-owned and unwritable.
extract_package() {
    local stale
    for stale in "${TEST_ROOT}"/ultiorganizer-*/; do
        [[ -d "${stale}" ]] || continue
        chown_test_root "$(id -u):$(id -g)"
        chmod -R u+rwX "${stale}"
        rm -rf "${stale}"
    done
    unzip -q "${ARCHIVE}" -d "${TEST_ROOT}"

    # install.php writes conf/config.inc.php and creates images/uploads/ as the
    # Apache user.
    docker run --rm -v "${TEST_ROOT}/${PACKAGE_NAME}:/pkg" "${HELPER_IMAGE}" \
        chown -R 33:33 /pkg/conf /pkg/images
}

reset_database() {
    compose exec -T db sh -lc \
        'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mariadb -uroot -e "
DROP DATABASE IF EXISTS ultiorganizer;
CREATE DATABASE ultiorganizer;
GRANT ALL ON ultiorganizer.* TO '"'"'ultiorganizer'"'"'@'"'"'%'"'"';"'
}

wait_for_install_page() {
    local i
    for ((i = 0; i < 60; i++)); do
        if [[ "$(curl -s -o /dev/null -w '%{http_code}' "${BASE_URL}/install.php")" == "200" ]]; then
            return 0
        fi
        sleep 1
    done
    echo "error: ${BASE_URL}/install.php did not answer 200 within 60s" >&2
    return 1
}

# Step 1 gates the Continue button on $passed, so an enabled Continue and no red
# row is proof the environment is actually installable.
verify_prerequisites() {
    local page failures
    page="$(curl -s "${BASE_URL}/install.php")"
    failures="$(grep -c 'color:red' <<< "${page}" || true)"

    if [[ "${failures}" != "0" ]] || grep -q "disabled='disabled'" <<< "${page}"; then
        echo "error: prerequisites check did not pass; open ${BASE_URL}/install.php" >&2
        sed 's/<[^>]*>/ /g' <<< "${page}" | tr -s ' \n' ' \n' | grep -v '^ *$' >&2
        return 1
    fi

    echo "Step 1 prerequisites: all ok, Continue enabled."
}

print_handoff() {
    cat <<EOF

Open ${BASE_URL}/install.php and run the wizard by hand.

  Step 2  Host address        db          (not localhost - that is the app container)
  Step 2  User/password/db    ultiorganizer / ultiorganizer / ultiorganizer
  Step 4  Base URL            ${BASE_URL}  (not http://localhost/ultiorganizer)

All three checks on step 6 should be green. Afterwards run:
  ${SCRIPT_DIR}/release-test.sh smoke
EOF
}

cmd_setup() {
    mkdir -p "${TEST_ROOT}"

    if [[ -n "${UO_TEST_ARCHIVE:-}" ]]; then
        ARCHIVE="${UO_TEST_ARCHIVE}"
    else
        local build_output
        build_output="$("${ROOT_DIR}/docs/release/build-release.sh" --install -y)"
        echo "${build_output}"
        ARCHIVE="$(sed -n 's/^Built //p' <<< "${build_output}")"
    fi

    if [[ ! -f "${ARCHIVE}" ]]; then
        echo "error: release package not found: ${ARCHIVE}" >&2
        exit 1
    fi

    PACKAGE_NAME="$(basename "${ARCHIVE}" .zip)"
    printf 'ARCHIVE=%q\nPACKAGE_NAME=%q\n' "${ARCHIVE}" "${PACKAGE_NAME}" > "${STATE_FILE}"

    extract_package
    write_compose_file

    compose up -d --force-recreate
    # --force-recreate replaces the containers but keeps the named volume, so a
    # setup following an earlier run would install over the previous database.
    reset_database
    wait_for_install_page
    verify_prerequisites
    print_handoff
}

cmd_reset() {
    load_state
    extract_package
    # Bring the stack up before touching the database: the db-healthy gate has
    # to pass before `compose exec db` can work on a stopped stack.
    compose up -d --force-recreate app
    reset_database
    wait_for_install_page
    verify_prerequisites
    print_handoff
}

# The installed app is the actual subject of the test: a file missing from the
# archive surfaces on a real page load, not in the wizard.
cmd_smoke() {
    load_state
    local package_dir="${TEST_ROOT}/${PACKAGE_NAME}"

    if [[ ! -f "${package_dir}/conf/config.inc.php" ]]; then
        echo "error: conf/config.inc.php is missing; run install.php first" >&2
        exit 1
    fi

    # index.php refuses to serve while install.php exists. Removing it is a step
    # of the install, and it has to happen host-side: the package root is owned
    # by the host user, so the Apache user cannot delete it.
    rm -f "${package_dir}/install.php"

    echo "Installed configuration:"
    grep -v "DB_PASSWORD" "${package_dir}/conf/config.inc.php" | grep "^define" | sed 's/^/  /'

    echo
    echo "Page checks (302 means a login redirect):"
    local path code
    for path in "/" "/?view=frontpage" "/?view=allteams" "/?view=allplayers" "/?view=games" \
        "/login/" "/scorekeeper/" "/spiritkeeper/" "/timekeeper/" "/mobile/" "/api/"; do
        code="$(curl -s -o /dev/null -w '%{http_code}' "${BASE_URL}${path}")"
        printf '  %-24s %s\n' "${path}" "${code}"
    done

    echo
    echo "PHP diagnostics on the front page:"
    if curl -s "${BASE_URL}/?view=frontpage" | grep -iE "fatal error|warning:|notice:|deprecated:"; then
        echo "  ^ investigate the above" >&2
    else
        echo "  none"
    fi

    echo
    echo "Apache error log:"
    local log
    log="$(compose logs app --since 10m 2>&1 | grep -iE "error|warn|fatal" | tail -10 || true)"
    echo "${log:-  none}"
}

cmd_teardown() {
    if [[ -f "${COMPOSE_FILE}" ]]; then
        compose down -v
    fi
    if [[ -d "${TEST_ROOT}" ]]; then
        chown_test_root "$(id -u):$(id -g)"
        chmod -R u+rwX "${TEST_ROOT}"
        rm -rf "${TEST_ROOT:?}"
    fi
    echo "Removed ${TEST_ROOT} and the ${PROJECT} stack."
}

case "${1:-}" in
    setup) cmd_setup ;;
    reset) cmd_reset ;;
    smoke) cmd_smoke ;;
    teardown) cmd_teardown ;;
    -h | --help | help) usage ;;
    *)
        usage >&2
        exit 1
        ;;
esac
