#!/usr/bin/env bash
# Build, extract and serve an Ultiorganizer release package in an isolated
# Docker stack so install.php can be run against it by hand.
#
# Usage: release-test.sh setup|reset|smoke|teardown [--help]
#
# Environment overrides:
#   UO_TEST_ROOT     test directory (default: <repo parent>/ultiorganizer-release-test)
#   UO_TEST_PROJECT  compose project name (default: uo-release-test)
#   UO_TEST_PORT     host port for the app (default: 8081)
#   UO_TEST_ARCHIVE  use this existing package instead of building one (setup)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
DEFAULT_TEST_ROOT="$(dirname "${ROOT_DIR}")/ultiorganizer-release-test"
TEST_ROOT="${UO_TEST_ROOT:-${DEFAULT_TEST_ROOT}}"
PROJECT="${UO_TEST_PROJECT:-uo-release-test}"
PORT="${UO_TEST_PORT:-8081}"
STATE_FILE="${TEST_ROOT}/.release-test-env"
COMPOSE_FILE="${TEST_ROOT}/compose.yaml"
BASE_URL="http://localhost:${PORT}"

# Any image with coreutils works; mariadb is already pulled by this stack.
HELPER_IMAGE="mariadb:10.11"

# Read the log destination from the ini the stack actually mounts rather than
# assuming it.
PHP_ERROR_LOG="$(sed -n 's/^error_log *= *//p' "${ROOT_DIR}/docs/dev/php.dev.ini" | head -1)"
PHP_ERROR_LOG="${PHP_ERROR_LOG:-/tmp/ultiorganizer-php-error.log}"

usage() {
    sed -n '2,11p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

compose() {
    docker compose -p "${PROJECT}" -f "${COMPOSE_FILE}" "$@"
}

# The web server writes as www-data (uid 33) and step 6 of the wizard hardens
# conf/ to 0555, so the host user can neither chown nor delete the tree
# afterwards. Borrow root from a throwaway container.
chown_test_root() {
    docker run --rm -v "${TEST_ROOT}:/work" "${HELPER_IMAGE}" chown -R "$1" /work
}

# The instance's port and project name are recorded by setup, so follow-up
# commands address the instance they belong to. Without that, a `smoke` after a
# `setup` on a non-default port would silently inspect whatever else is serving
# on 8081 and report plausible-looking results for the wrong stack. An explicit
# environment override still wins.
load_state() {
    if [[ ! -f "${STATE_FILE}" ]]; then
        echo "error: ${STATE_FILE} not found; run 'release-test.sh setup' first" >&2
        exit 1
    fi
    # shellcheck source=/dev/null
    source "${STATE_FILE}"
    PROJECT="${UO_TEST_PROJECT:-${STATE_PROJECT:-${PROJECT}}}"
    PORT="${UO_TEST_PORT:-${STATE_PORT:-${PORT}}}"
    BASE_URL="http://localhost:${PORT}"
}

write_compose_file() {
    cat > "${COMPOSE_FILE}" <<EOF
# Generated by docs/ai/test-release-install/scripts/release-test.sh.
# The web root is the extracted release package, not the git checkout.
services:
  app:
    build:
      context: ${ROOT_DIR}
      dockerfile: docs/dev/Dockerfile.app
    depends_on:
      db:
        condition: service_healthy
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      XDEBUG_MODE: "off"
    ports:
      - "${PORT}:80"
    volumes:
      - ./${PACKAGE_NAME}:/var/www/html
      - ${ROOT_DIR}/docs/dev/php.dev.ini:/usr/local/etc/php/conf.d/zz-local-dev.ini:ro

  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ultiorganizer
      MYSQL_USER: ultiorganizer
      MYSQL_PASSWORD: ultiorganizer
      MYSQL_ROOT_PASSWORD: changeme
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=127.0.0.1", "--user=root", "--password=changeme"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - release-test-db-data:/var/lib/mysql

volumes:
  release-test-db-data:
EOF
}

# Removes every previously extracted package, not just the current one: the
# directory name carries the commit hash, so building at a new commit would
# otherwise leave the old tree behind, www-data-owned and unwritable.
extract_package() {
    local stale
    for stale in "${TEST_ROOT}"/ultiorganizer-*/; do
        [[ -d "${stale}" ]] || continue
        chown_test_root "$(id -u):$(id -g)"
        chmod -R u+rwX "${stale}"
        rm -rf "${stale}"
    done
    unzip -q "${ARCHIVE}" -d "${TEST_ROOT}"

    # install.php writes conf/config.inc.php and creates images/uploads/ as the
    # Apache user.
    docker run --rm -v "${TEST_ROOT}/${PACKAGE_NAME}:/pkg" "${HELPER_IMAGE}" \
        chown -R 33:33 /pkg/conf /pkg/images
}

reset_database() {
    compose exec -T db sh -lc \
        'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mariadb -uroot -e "
DROP DATABASE IF EXISTS ultiorganizer;
CREATE DATABASE ultiorganizer;
GRANT ALL ON ultiorganizer.* TO '"'"'ultiorganizer'"'"'@'"'"'%'"'"';"'
}

wait_for_install_page() {
    local i
    for ((i = 0; i < 60; i++)); do
        if [[ "$(curl -s -o /dev/null -w '%{http_code}' "${BASE_URL}/install.php")" == "200" ]]; then
            return 0
        fi
        sleep 1
    done
    echo "error: ${BASE_URL}/install.php did not answer 200 within 60s" >&2
    return 1
}

# Step 1 gates the Continue button on $passed, so an enabled Continue and no red
# row is proof the environment is actually installable.
verify_prerequisites() {
    local page failures
    page="$(curl -s "${BASE_URL}/install.php")"
    failures="$(grep -c 'color:red' <<< "${page}" || true)"

    if [[ "${failures}" != "0" ]] || grep -q "disabled='disabled'" <<< "${page}"; then
        echo "error: prerequisites check did not pass; open ${BASE_URL}/install.php" >&2
        sed 's/<[^>]*>/ /g' <<< "${page}" | tr -s ' \n' ' \n' | grep -v '^ *$' >&2
        return 1
    fi

    echo "Step 1 prerequisites: all ok, Continue enabled."
}

print_handoff() {
    # The state file lives inside the test root, so a custom root cannot be
    # recovered from it — every follow-up command has to carry it explicitly.
    local prefix=""
    if [[ "${TEST_ROOT}" != "${DEFAULT_TEST_ROOT}" ]]; then
        prefix="UO_TEST_ROOT=$(printf '%q' "${TEST_ROOT}") "
    fi

    cat <<EOF

Open ${BASE_URL}/install.php and run the wizard by hand.

  Step 2  Host address        db          (not localhost - that is the app container)
  Step 2  User/password/db    ultiorganizer / ultiorganizer / ultiorganizer
  Step 4  Base URL            ${BASE_URL}  (not http://localhost/ultiorganizer)

All three checks on step 6 should be green. Afterwards run:
  ${prefix}${SCRIPT_DIR}/release-test.sh smoke
EOF
}

cmd_setup() {
    mkdir -p "${TEST_ROOT}"

    if [[ -n "${UO_TEST_ARCHIVE:-}" ]]; then
        ARCHIVE="${UO_TEST_ARCHIVE}"
    else
        local build_output
        build_output="$("${ROOT_DIR}/docs/release/build-release.sh" --install -y)"
        echo "${build_output}"
        ARCHIVE="$(sed -n 's/^Built //p' <<< "${build_output}")"
    fi

    if [[ ! -f "${ARCHIVE}" ]]; then
        echo "error: release package not found: ${ARCHIVE}" >&2
        exit 1
    fi

    PACKAGE_NAME="$(basename "${ARCHIVE}" .zip)"
    printf 'ARCHIVE=%q\nPACKAGE_NAME=%q\nSTATE_PROJECT=%q\nSTATE_PORT=%q\n' \
        "${ARCHIVE}" "${PACKAGE_NAME}" "${PROJECT}" "${PORT}" > "${STATE_FILE}"

    extract_package
    write_compose_file

    compose up -d --force-recreate
    # --force-recreate replaces the containers but keeps the named volume, so a
    # setup following an earlier run would install over the previous database.
    reset_database
    wait_for_install_page
    verify_prerequisites
    print_handoff
}

cmd_reset() {
    load_state
    extract_package
    # Bring the stack up before touching the database: the db-healthy gate has
    # to pass before `compose exec db` can work on a stopped stack.
    compose up -d --force-recreate app
    reset_database
    wait_for_install_page
    verify_prerequisites
    print_handoff
}

# The installed app is the actual subject of the test: a file missing from the
# archive surfaces on a real page load, not in the wizard.
cmd_smoke() {
    load_state
    local package_dir="${TEST_ROOT}/${PACKAGE_NAME}"
    local failures=0

    if [[ ! -f "${package_dir}/conf/config.inc.php" ]]; then
        echo "error: conf/config.inc.php is missing; run install.php first" >&2
        exit 1
    fi

    # index.php refuses to serve while install.php exists. Removing it is a step
    # of the install, and it has to happen host-side: the package root is owned
    # by the host user, so the Apache user cannot delete it.
    rm -f "${package_dir}/install.php"

    echo "Installed configuration:"
    grep -v "DB_PASSWORD" "${package_dir}/conf/config.inc.php" | grep "^define" | sed 's/^/  /'

    local body asset_list redirect_apps
    body="$(mktemp)"
    asset_list="$(mktemp)"
    redirect_apps="$(mktemp)"

    # Each route carries the status its contract says it must answer, so an
    # access or routing regression fails the run rather than passing as merely
    # "not an error": a scorekeeper that stops redirecting to login, or a
    # timekeeper that starts, is exactly what this should catch. The
    # expectations assume an install with the default settings.
    echo
    echo "Page checks (302 means a login redirect):"
    local entry path expected code page_dir asset url
    for entry in "/|302" "/?view=frontpage|200" "/?view=allteams|200" "/?view=allplayers|200" \
        "/?view=games|200" "/login/|302" "/scorekeeper/|302" "/spiritkeeper/|200" \
        "/timekeeper/|200" "/mobile/|302" "/api/|404"; do
        path="${entry%|*}"
        expected="${entry##*|}"
        code="$(curl -s -o "${body}" -w '%{http_code}' "${BASE_URL}${path}")"

        if [[ "${code}" == "${expected}" ]]; then
            printf '  %-24s %s\n' "${path}" "${code}"
        else
            printf '  %-24s %s (expected %s)\n' "${path}" "${code}" "${expected}"
            failures=$((failures + 1))
        fi

        if [[ "${code}" -ge 300 && "${code}" -lt 400 && "${path}" != "/" && "${path}" == */ ]]; then
            echo "${path//\//}" >> "${redirect_apps}"
        fi

        [[ "${code}" == "200" ]] || continue

        # display_errors is On in php.dev.ini, so diagnostics land in the page
        # body. Scan every page that renders: php.dev.ini also sends error_log
        # to a file inside the container, so `compose logs app` shows none of
        # them, and a broken standalone page would otherwise pass unnoticed.
        if grep -iqE "<b>(fatal error|parse error|warning|notice|deprecated)</b>|(fatal|parse) error:" "${body}"; then
            echo "  ^ PHP diagnostics in the body of ${path}" >&2
            failures=$((failures + 1))
        fi

        # Collect assets from every app that renders, not only the front page:
        # the standalone apps pull their own scripts, so a front-page-only crawl
        # would never request script/timekeeper.js. Relative references resolve
        # against the page's own directory; curl normalizes the ../ segments.
        page_dir="${path%%\?*}"
        page_dir="${page_dir%/}"
        while read -r asset; do
            [[ -n "${asset}" ]] || continue
            case "${asset}" in
                http*) url="${asset}" ;;
                /*) url="${BASE_URL}${asset}" ;;
                *) url="${BASE_URL}${page_dir}/${asset}" ;;
            esac
            echo "${url}" >> "${asset_list}"
        done < <(grep -oE "(href|src)=['\"][^'\"]+\.(css|js|png|jpg|jpeg|gif|svg|ico)([?][^'\"]*)?['\"]" "${body}" |
            sed "s/^[a-z]*=['\"]//;s/['\"]$//")
    done

    # curl fetches the HTML only, so a stylesheet, script or image missing from
    # the package leaves the page a healthy 200. Follow the references.
    echo
    echo "Assets referenced by those pages:"
    local asset_count=0 asset_failures=0 css_list
    css_list="$(mktemp)"

    # A stylesheet that loads fine can still point at an image the package
    # omits, and nothing on the page requests it. Collect url() targets from
    # every stylesheet fetched, resolved against the stylesheet's own directory,
    # and check those too.
    check_asset_list() {
        local list="$1" derive="$2" css_dir ref
        while read -r url; do
            [[ -n "${url}" ]] || continue
            code="$(curl -s -o "${body}" -w '%{http_code}' "${url}")"
            asset_count=$((asset_count + 1))
            if [[ "${code}" != "200" ]]; then
                printf '  %-64s %s\n' "${url#"${BASE_URL}"}" "${code}"
                asset_failures=$((asset_failures + 1))
                continue
            fi

            [[ "${derive}" == "derive" && "${url}" == *.css ]] || continue
            css_dir="${url%/*}"
            while read -r ref; do
                [[ -n "${ref}" ]] || continue
                case "${ref}" in
                    data:* | http*) continue ;;
                    /*) echo "${BASE_URL}${ref}" >> "${css_list}" ;;
                    *) echo "${css_dir}/${ref}" >> "${css_list}" ;;
                esac
            done < <(perl -0777 -pe 's{/\*.*?\*/}{}gs' "${body}" |
                grep -oE "url\(['\"]?[^)'\"]+['\"]?\)" |
                sed -E "s/^url\(['\"]?//;s/['\"]?\)$//")
        done < <(sort -u "${list}")
    }

    check_asset_list "${asset_list}" derive
    if [[ -s "${css_list}" ]]; then
        check_asset_list "${css_list}" no-derive
    fi
    rm -f "${css_list}"

    echo "  ${asset_count} checked, ${asset_failures} failed"
    failures=$((failures + asset_failures))

    # An app that redirects to login never renders, so a crawl cannot reach its
    # own scripts without credentials — and smoke has none, since the developer
    # creates the admin account in the wizard. Take the references from the
    # app's source in the package instead: they are plain literals that a
    # runtime prefix resolves to the document root.
    echo
    echo "Assets of redirecting apps (read from the package source):"
    local app ref static_count=0 static_failures=0
    while read -r app; do
        [[ -n "${app}" && -d "${package_dir}/${app}" ]] || continue
        while read -r ref; do
            [[ -n "${ref}" ]] || continue
            code="$(curl -s -o /dev/null -w '%{http_code}' "${BASE_URL}/${ref}")"
            static_count=$((static_count + 1))
            if [[ "${code}" != "200" ]]; then
                printf '  %-64s %s\n' "${app}: ${ref}" "${code}"
                static_failures=$((static_failures + 1))
            fi
        done < <(grep -rhoE "['\"](script|images)/[A-Za-z0-9_./-]+\.(js|css|png|jpg|jpeg|gif|svg|ico)" \
            "${package_dir}/${app}" | sed "s/^['\"]//" | sort -u)
    done < <(sort -u "${redirect_apps}")
    echo "  ${static_count} checked, ${static_failures} failed"
    failures=$((failures + static_failures))

    # A missing API router would produce Apache's own HTML 404, which is
    # indistinguishable from the router's 404 by status code alone.
    echo
    echo "API router:"
    if curl -s "${BASE_URL}/api/" | grep -q '"status":"error"'; then
        echo "  ok (router answered with JSON)"
    else
        echo "  FAILED: /api/ did not return the router's JSON error body" >&2
        failures=$((failures + 1))
    fi

    echo
    echo "Apache error log:"
    local log
    log="$(compose logs app --since 10m 2>&1 | grep -iE "error|warn|fatal" | tail -10 || true)"
    echo "${log:-  none}"

    # php.dev.ini routes error_log to a file inside the container, so this is
    # the only place PHP's own log is visible. Shown as evidence rather than
    # counted: it accumulates across the whole life of the container.
    echo
    echo "PHP error log (${PHP_ERROR_LOG}, last 10 lines):"
    log="$(compose exec -T app sh -lc "tail -10 ${PHP_ERROR_LOG} 2>/dev/null" || true)"
    echo "${log:-  none}"

    rm -f "${body}" "${asset_list}" "${redirect_apps}"

    # Exit status is the verdict: automation calling smoke must not read a
    # broken release as verified just because the command printed something.
    echo
    if [[ "${failures}" -eq 0 ]]; then
        echo "Smoke test passed."
    else
        echo "Smoke test FAILED: ${failures} check(s)." >&2
        return 1
    fi
}

cmd_teardown() {
    if [[ -f "${STATE_FILE}" ]]; then
        load_state
    fi
    if [[ -f "${COMPOSE_FILE}" ]]; then
        compose down -v
    fi
    if [[ -d "${TEST_ROOT}" ]]; then
        chown_test_root "$(id -u):$(id -g)"
        chmod -R u+rwX "${TEST_ROOT}"
        rm -rf "${TEST_ROOT:?}"
    fi
    echo "Removed ${TEST_ROOT} and the ${PROJECT} stack."
}

case "${1:-}" in
    setup) cmd_setup ;;
    reset) cmd_reset ;;
    smoke) cmd_smoke ;;
    teardown) cmd_teardown ;;
    -h | --help | help) usage ;;
    *)
        usage >&2
        exit 1
        ;;
esac
