module.exports = {
	extends: [require.resolve("stylelint-config-standard")],
	ignoreFiles: [
		"dist/**",
		"live/**",
		"reports/**",
		"vendor/**",
	],
	rules: {
		"alpha-value-notation": null,
		"color-function-alias-notation": null,
		"color-function-notation": null,
		"color-hex-length": null,
		"comment-empty-line-before": null,
		"comment-whitespace-inside": null,
		"custom-property-pattern": null,
		"declaration-block-no-redundant-longhand-properties": null,
		"declaration-property-value-keyword-no-deprecated": null,
		"font-family-name-quotes": null,
		"function-url-quotes": null,
		"hue-degree-notation": null,
		"length-zero-no-unit": null,
		"media-feature-range-notation": null,
		"no-descending-specificity": null,
		"property-no-vendor-prefix": null,
		"selector-class-pattern": null,
		"selector-id-pattern": null,
		"selector-type-no-unknown": [
			true,
			{
				ignore: ["custom-elements"],
				ignoreTypes: ["yuicalendar"],
			},
		],
		"shorthand-property-no-redundant-values": null,
		"value-keyword-case": null,
		"value-no-vendor-prefix": null,
	},
};
